POST https://api-node-fekw.onrender.com/videos
Content-Type: application/json


{
    "title": "Video nodejs",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET https://api-node-fekw.onrender.com/videos


###



PUT https://api-node-fekw.onrender.com/videos/a848636a-5c39-4d1e-8e49-d9997d1e387c
Content-Type: application/json


{
    "title": "Video 02",
    "description": "Esse é o 02 video",
    "duration": 380
}


###

DELETE https://api-node-fekw.onrender.com/videos/a848636a-5c39-4d1e-8e49-d9997d1e387c